### ISSUE TITLE
Discussing possible enhancements

### ISSUE THREAD

**Issue by justusbunsi** [reposilite-playground/reposilite-helm#9]
Hi 👋. While configuring the Helm Chart, I found myself patching the generated resources to match my requirements. Thus, I'd like to discuss some enhancements that I'd like to implement:

- Configurable `automountServiceAccountToken` for ServiceAccount, the default value is `true` and I couldn't find a need to actually have that token mounted into the containers. #10 
- Configurable `securityContext` on Pod level (maybe on per-container basis). This allows running the container as non-root user. #11 
- Support for mounting additional volumes into the runtime container. Currently the Helm Chart only supports mounting additional volumes into initContainers, as far as I found. Mounting additional volumes into the runtime container would allow mounting configuration files without persisting them (e.g. in GitOps contexts they are already persistent in the git repository). #12

I decided to open a summarized issue for discussion instead of one per sugestion. Hope this is ok.

**Comment by dzikoysk** [comment]
I don't have much experience with Helm, so I'd rather wait for @joshuasing's feedback.

**Comment by joshuasing** [comment]
Hi, sorry for the delay in my response, the notification must have gotten lost amongst the rest of my daily notifications.

I am not currently the most experienced with Helm charts unfortunately, but I believe everything you mentioned would be great additions. I have recently discovered a bunch of other issues/annoyances with the chart (e.g. hard to create HA environments), so I'll hopefully submit a few PRs later this week to help improve some things.

**Comment by justusbunsi** [comment]
> Hi, sorry for the delay in my response, the notification must have gotten lost amongst the rest of my daily notifications.

No worries. 🙂

If you are open to it, I can provide PRs for the additions above.

**Comment by dzikoysk** [comment]
Sure, feel free to submit PR :) I'd appriciate a short description per each PR why given change is needed & a note about used values (defaults).

**Comment by justusbunsi** [comment]
@dzikoysk The recent PR merges resulted in broken builds on main. Is it due to me not bumping the version of the Chart in each PR?
EDIT: 🚀 Nevermind. Saw you already bumped the chart.

**Comment by dzikoysk** [comment]
Thanks for your contribution, let me know in case of further issues with this chart. For now, we can just wait to see if it works fine for everyone 😅

**Comment by justusbunsi** [comment]
I am going to update my chart version tomorrow and see if all my customization of the rendered files is obsolete now. It should be. Thanks to all the maintainers of the Reposilite ecosystem for their time.

Let's close this issue as complete for now.
